#!/usr/bin/env python

import os
import matplotlib.pyplot as plt
import numpy as np

plotPath = './post'
dataPath = plotPath + '/data'
if os.path.exists(plotPath) == False:
    os.makedirs(plotPath)
if os.path.exists(dataPath) == False:
    os.makedirs(dataPath)
#1. X size
fin  = open('fort.24','r')
linesList  = fin.readlines()
fin .close()    
linesList  = [line.split() for line in linesList ]

z   = [x[0] for x in linesList]
rms = [x[2] for x in linesList]

plt1 = plt.plot(z, rms, 'r',lable='xRms')

fin = open('fort.27','r')
linesList = fin.readlines()
fin.close()    
linesList = [line.split() for line in linesList]

z   = [x[0] for x in linesList]
mx  = [x[1] for x in linesList]

plt2 = plt.plot(z, mx, 'b',lable='xMax')

plt.xlabel('z distance (m)')
plt.ylabel('rms,max in X (m)')
plt.legend(handles=[plt1,plt2],['x','xM'])
plt.savefig(plotPath+'/SizeX.png')

#2. Y size
fin  = open('fort.25','r')
linesList  = fin.readlines()
fin .close()    
linesList  = [line.split() for line in linesList ]

z   = [x[0] for x in linesList]
rms = [x[2] for x in linesList]

plt.plot(z, rms, 'r',lable='yRms')

fin = open('fort.27','r')
linesList = fin.readlines()
fin.close()    
linesList = [line.split() for line in linesList]

z   = [x[0] for x in linesList]
mx  = [x[3] for x in linesList]

plt.plot(z, mx, 'b',lable='yMax')
plt.xlabel('z distance (m)')
plt.ylabel('rms,max in Y (m)')
plt.legend()
plt.savefig(plotPath+'/SizeY.png')

#3. Z size
fin  = open('fort.26','r')
linesList  = fin.readlines()
fin .close()    
linesList  = [line.split() for line in linesList ]

z   = [x[0] for x in linesList]
rms = [x[2] for x in linesList]

plt.plot(z, rms, 'r',lable='zRms')

fin = open('fort.27','r')
linesList = fin.readlines()
fin.close()    
linesList = [line.split() for line in linesList]

z   = [x[0] for x in linesList]
mx  = [x[5] for x in linesList]

plt.plot(z, mx, 'b',lable='zMax')
plt.xlabel('z distance (m)')
plt.ylabel('rms,max in Z (m)')
plt.legend()
plt.savefig(plotPath+'/SizeZ.png')

#3. X and Y emittance
fin  = open('fort.24','r')
linesList  = fin.readlines()
fin .close()    
linesList  = [line.split() for line in linesList ]

z   = [x[0] for x in linesList]
rms = [x[6] for x in linesList]

plt.plot(z, rms, 'r',lable='emit.nor.x')

fin = open('fort.25','r')
linesList = fin.readlines()
fin.close()    
linesList = [line.split() for line in linesList]

z   = [x[0] for x in linesList]
mx  = [x[6] for x in linesList]

plt.plot(z, mx, 'b',lable='emit.nor.y')
plt.xlabel('z distance (m)')
plt.ylabel('emittance at X and Y (m*rad)')
plt.legend()
plt.savefig(plotPath+'/SizeZ.png')

